# Generated by Django 5.2.8 on 2025-12-23 10:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_alter_news_options_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='address',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='email',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='phone',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='educational_activities',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='history',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='learning_activities',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='scientific_activities',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='full_name',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='profile',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
